apiVersion: apps/v1
kind: Deployment
metadata:
  name: hanoi-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hanoi
  template:
    metadata:
      labels:
        app: hanoi
    spec:
      containers:
      - name: hanoi
        image: hanoi:1.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
